name: Build and deploy Node.js app to Azure Web App - shilltube-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm prisma generate
          pnpm build

      - name: Prepare app for deployment
        run: |
          mkdir deploy
          cp -r dist deploy/
          cp package.json pnpm-lock.yaml deploy/

      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_345115C22E164ABE80EAFD705BF5F7F9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7FE594352325425ABC6F1C0156B59289 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB66D746014540FE94BB9B64CE308C02 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shilltube-backend'
          slot-name: 'Production'
          package: .
